# All Vagrant configuration is done below.
Vagrant.configure("2") do |config|
  # Use "ubuntu/bionic64" box
  config.vm.box = "ubuntu/bionic64"

  # Create a private network, which allows host-only access to the machine using a specific IP.
  config.vm.network "private_network", ip: "192.168.56.200"

  # config.ssh.username = "ubuntu"
  # config.ssh.password = "fbcd1ed4fe8c83b157dc6e0f"
  # config.ssh.username = "vagrant"
  # config.ssh.password = "vagrant"

  # Provider-specific configuration so you can fine-tune various backing providers for Vagrant.
  config.vm.provider "virtualbox" do |vb|
    # Display the VirtualBox GUI when booting the machine
    vb.gui = true

    # Customize the amount of memory on the VM:
    vb.memory = "4096"
  end

  # Enable provisioning with a shell script.
  config.vm.provision "shell", inline: <<-SHELL
    sudo locale-gen en_GB.UTF-8
    sudo update-locale LANG="en_GB.UTF-8"

    sudo apt-get update
    sudo apt-get upgrade -y

    sudo apt-get install -y ubuntu-desktop

    sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys E298A3A825C0D65DFD57CBB651716619E084DAB9
    sudo add-apt-repository 'deb https://cloud.r-project.org/bin/linux/ubuntu bionic-cran40/'
    sudo apt-get update
    sudo apt-get install -y r-base

    sudo apt-get install -y libclang-dev
    sudo curl https://download1.rstudio.org/desktop/bionic/amd64/rstudio-1.3.1093-amd64.deb --output /tmp/rstudio-1.3.1093-amd64.deb
    sudo dpkg --install /tmp/rstudio-1.3.1093-amd64.deb
    sudo apt-get install -f
    sudo rm -f /tmp/rstudio-1.3.1093-amd64.deb

    sudo apt-get install -y libgit2-dev libssl-dev libssh2-1-dev libxml2-dev libcurl4-gnutls-dev libfontconfig1-dev libfreetype6-dev libpng-dev libtiff5-dev libjpeg-dev libgsl-dev
    sudo -i -u vagrant mkdir -p ~vagrant/R/x86_64-pc-linux-gnu-library/4.0
    sudo -i -u vagrant R -q -e "install.packages(c('devtools','covr'), dependencies=TRUE, repos='https://cloud.r-project.org')"
    sudo -i -u vagrant R -q -e "install.packages(c('fields','metafor','ggplot2','gridExtra','data.table'), dependencies=TRUE, repos='https://cloud.r-project.org')"
    sudo -i -u vagrant R -q -e "install.packages(c('DSI','DSOpal','DSLite'), dependencies=TRUE, repos='https://cloud.r-project.org')"
    sudo -i -u vagrant R -q -e "install.packages(c('DescTools','e1071'), dependencies=TRUE, repos='https://cloud.r-project.org')"
    sudo -i -u vagrant R -q -e "install.packages(c('RANN','reshape2'), dependencies=TRUE, repos='https://cloud.r-project.org')"

    sudo -i -u vagrant git clone https://github.com/datashield/dsBase.git -b master
    sudo -i -u vagrant git clone https://github.com/datashield/dsBaseClient.git -b master
  SHELL
end
