# Modules from the forge
mod 'puppetlabs/stdlib', '5.2.0'
mod 'puppetlabs/apt', '6.3.0'
mod 'stahnma/epel', '1.3.1'
mod 'nanliu/staging', '1.0.3'
mod 'puppetlabs/mysql', '8.1.0'
mod 'adrien/alternatives', '0.3.0'
mod 'puppetlabs/firewall', '1.15.3'
mod 'heini-wait_for', '2.0.1'

mod 'opal',
  :git => 'https://github.com/datashield/puppet-opal',
  :branch => '6.1.1'
mod 'r',
  :git => 'https://github.com/datashield/puppet-r',
  :branch => '6.1.1'
mod 'datashield',
  :git => 'https://github.com/datashield/puppet-datashield',
  :branch => '6.1.1'
mod 'mongodb',
  :git => 'https://github.com/datashield/puppet-mongodb',
  :branch => '6.1.1'
