# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrant configuration file for configuring 3 Ubuntu datashield servers provisioned with datashield_testdata with the
# also a datashield client provisioned with the datashield_client puppet environment. All created on the Google Compute
# Engine
#

Vagrant.configure(2) do |config|
  # See https://docs.vagrantup.com. for vagrant config info

  config.vm.box = "gce"
  config.vm.box_url = 'https://github.com/mitchellh/vagrant-google/raw/master/google.box'

  # Define a datashield client
  config.vm.define "client" do |client|
    client.vm.provider :google do |google|
      # Make sure to set this to trigger the zone_config
      google.zone = "europe-west1-d" # Zone where the computer is going to be (keep all computers in the same zoon)

      google.zone_config "europe-west1-d" do |zone1f|
        zone1f.name = "datashield-client" # Name of the VM to spin up
        zone1f.image = "ubuntu-1404-trusty-v20160222" # Image of the VM to spin up
        zone1f.machine_type = "n1-standard-1" # Google cloud compute machine type
        zone1f.zone = "europe-west1-d" # Keep this the same as zone
        zone1f.disk_size = 10 # Size of the disk (GB)
        zone1f.network = "client-external" # Which network for the VM to use
      end
    end
    client.vm.provision :shell, :path => '../../scripts/ubuntu/setup.sh'
    client.vm.provision :shell, :inline => 'cd /tmp/vagrant-puppet/environments/datashield_client && r10k -v info puppetfile install'
    client.vm.provision "puppet" do |puppet|
      puppet.environment_path = "../../puppet/environments"
      puppet.environment = "datashield_client"
    end
  end

  config.vm.define "datashield1" do |datashield1|
    datashield1.vm.provider :google do |google|
      # Make sure to set this to trigger the zone_config
      google.zone = "europe-west1-d" # Zone where the computer is going to be (keep all computers in the same zoon)

      google.zone_config "europe-west1-d" do |zone1f|
        zone1f.name = "datashield-server1" # Name of the VM to spin up
        zone1f.image = "ubuntu-1404-trusty-v20160222" # Image of the VM to spin up
        zone1f.machine_type = "n1-standard-1" # Google cloud compute machine type
        zone1f.zone = "europe-west1-d" # Keep this the same as zone
        zone1f.disk_size = 10 # Size of the disk (GB)
        zone1f.network = "server-external" # Which network for the VM to use
      end
    end
    datashield1.vm.provision :shell, :path => '../../scripts/ubuntu/setup.sh'
    datashield1.vm.provision :shell, :inline => 'cd /tmp/vagrant-puppet/environments/datashield_testdata && r10k -v info puppetfile install'
    datashield1.vm.provision "puppet" do |puppet|
      puppet.environment_path = "../../puppet/environments"
      puppet.environment = "datashield_testdata"
    end
  end

  config.vm.define "datashield2" do |datashield2|
    datashield2.vm.provider :google do |google|
      # Make sure to set this to trigger the zone_config
      google.zone = "europe-west1-d" # Zone where the computer is going to be (keep all computers in the same zoon)

      google.zone_config "europe-west1-d" do |zone1f|
        zone1f.name = "datashield-server2" # Name of the VM to spin up
        zone1f.image = "ubuntu-1404-trusty-v20160222" # Image of the VM to spin up
        zone1f.machine_type = "n1-standard-1" # Google cloud compute machine type
        zone1f.zone = "europe-west1-d" # Keep this the same as zone
        zone1f.disk_size = 10 # Size of the disk (GB)
        zone1f.network = "server-external" # Which network for the VM to use
      end
    end
    datashield2.vm.provision :shell, :path => '../../scripts/ubuntu/setup.sh'
    datashield2.vm.provision :shell, :inline => 'cd /tmp/vagrant-puppet/environments/datashield_testdata && r10k -v info puppetfile install'
    datashield2.vm.provision "puppet" do |puppet|
      puppet.environment_path = "../../puppet/environments"
      puppet.environment = "datashield_testdata"
    end
  end

  config.vm.define "datashield3" do |datashield3|
    datashield3.vm.provider :google do |google|
      # Make sure to set this to trigger the zone_config
      google.zone = "europe-west1-d" # Zone where the computer is going to be (keep all computers in the same zoon)

      google.zone_config "europe-west1-d" do |zone1f|
        zone1f.name = "datashield-server3" # Name of the VM to spin up
        zone1f.image = "ubuntu-1404-trusty-v20160222" # Image of the VM to spin up
        zone1f.machine_type = "n1-standard-1" # Google cloud compute machine type
        zone1f.zone = "europe-west1-d" # Keep this the same as zone
        zone1f.disk_size = 10 # Size of the disk (GB)
        zone1f.network = "server-external" # Which network for the VM to use
      end
    end
    datashield3.vm.provision :shell, :path => '../../scripts/ubuntu/setup.sh'
    datashield3.vm.provision :shell, :inline => 'cd /tmp/vagrant-puppet/environments/datashield_testdata && r10k -v info puppetfile install'
    datashield3.vm.provision "puppet" do |puppet|
      puppet.environment_path = "../../puppet/environments"
      puppet.environment = "datashield_testdata"
    end
  end

end
