# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrant configuration file for a Centos VM running a datashield client as provisioned by the datashield_client
# puppet environment, the VM will be run on the Google computer cloud.
#

Vagrant.configure(2) do |config|
  # See https://docs.vagrantup.com. for vagrant config info

  config.vm.box = "gce"
  config.vm.box_url = 'https://github.com/mitchellh/vagrant-google/raw/master/google.box'

  # Setup Google:
  #
  config.vm.provider :google do |google|

    config.ssh.pty= true
    # Make sure to set this to trigger the zone_config
    google.zone = "europe-west1-d" # Zone where the computer is going to be (keep all computers in the same zoon)

    google.zone_config "europe-west1-d" do |zone1f|
      zone1f.name = "datashield-client-centos" # Name of the VM to spin up
      zone1f.image = "centos-7-v20160219" # Image of the VM to spin up
      zone1f.machine_type = "n1-standard-1" # Google cloud compute machine type
      zone1f.zone = "europe-west1-d" # Keep this the same as zone
      zone1f.disk_size = 10 # Size of the disk (GB)
      zone1f.network = "default" # Which network for the VM to use
    end
  end

  #
  # Provisioning of the VM. Run the setup script. Then run r10k to install puppet modules. Then run the puppet
  # for the environment you wish to setup.
  #
  config.vm.provision :shell, :path => '../../scripts/centos/setup.sh'
  config.vm.provision :shell, :inline => 'cd /tmp/vagrant-puppet/environments/datashield_client && r10k -v info puppetfile install'
  config.vm.provision "puppet" do |puppet|
    puppet.environment_path = "../../puppet/environments"
    puppet.environment = "datashield_client"
  end
end
