# Modules from the forge
mod 'puppetlabs/stdlib', '4.9.0'
mod 'puppetlabs/apt', '2.2.0'
mod 'stahnma/epel', '1.1.1'
mod 'nanliu/staging', '1.0.3'
mod 'puppetlabs/mysql', '3.6.1'
mod 'adrien/alternatives', '0.3.0'
mod 'puppetlabs/firewall', '1.7.2'

mod 'datashield',
  :git => 'https://github.com/datashield/puppet-datashield'
mod 'mongodb',
  :git => 'https://github.com/datashield/puppet-mongodb'
