# Modules from the forge
mod 'puppetlabs/stdlib', '4.25.1'
mod 'puppetlabs/apt', '4.5.1'
mod 'stahnma/epel', '1.3.0'
mod 'nanliu/staging', '1.0.3'
mod 'puppetlabs/mysql', '5.4.0'
mod 'adrien/alternatives', '0.3.0'
mod 'puppetlabs/firewall', '1.12.0'
mod 'heini-wait_for', '2.0.1'

mod 'opal',
  :git => 'https://github.com/datashield/puppet-opal',
  :branch => 'ubuntu16'
mod 'r',
  :git => 'https://github.com/datashield/puppet-r',
  :branch => 'ubuntu16'
mod 'datashield',
  :git => 'https://github.com/datashield/puppet-datashield',
  :branch => 'ubuntu16'
mod 'mongodb',
  :git => 'https://github.com/datashield/puppet-mongodb',
  :branch => 'ubuntu16'
