# Modules from the forge
mod 'puppetlabs/stdlib', '6.0.0'
mod 'puppetlabs/apt', '7.0.1'
mod 'stahnma/epel', '1.3.1'
mod 'nanliu/staging', '1.0.3'
mod 'puppetlabs/mysql', '9.0.0'
mod 'adrien/alternatives', '0.3.0'
mod 'puppetlabs/firewall', '2.0.0'
mod 'heini/wait_for', '2.0.1'

mod 'opal',
  :git => 'https://github.com/datashield/puppet-opal',
  :branch => 'ubuntu16'
mod 'r',
  :git => 'https://github.com/datashield/puppet-r',
  :branch => 'ubuntu16'
mod 'datashield',
  :git => 'https://github.com/datashield/puppet-datashield',
  :branch => 'ubuntu16'
mod 'mongodb',
  :git => 'https://github.com/datashield/puppet-mongodb',
  :branch => 'ubuntu16'
