# Modules from the forge
mod 'puppetlabs/stdlib', '4.9.0'
mod 'puppetlabs/apt', '2.2.0'
mod 'stahnma/epel', '1.1.1'
mod 'nanliu/staging', '1.0.3'
mod 'adrien/alternatives', '0.3.0'
mod 'puppetlabs/firewall', '1.7.2'
mod 'basti1302/wait_for', '0.3.0'
mod 'cpick/gdebi', '0.1.1'
mod 'maestrodev/wget', '1.7.1'
mod 'r',
  :git => 'https://github.com/nparley/puppet-r'
mod 'datashield',
  :git => 'https://github.com/nparley/puppet-datashield'