# -*- mode: ruby -*-
# vi: set ft=ruby :

# This Vagrantfile will create a datashield db server machine using the datashield_db_server puppet environment built on
# top of a Ubuntu vagrant box. By default the VM has 1GB of RAM and the private IP address of the machine is 192.168.2.20.
#
Vagrant.configure(2) do |config|
  # See https://docs.vagrantup.com. for vagrant config info

  # Support status
  system("echo '**************************************************************'")
  system("echo '*                                                            *'")
  system("echo '*                       Unmaintained                         *'")
  system("echo '*                                                            *'")
  system("echo '*  This Vagrantfile, and related files, are not maintained.  *'")
  system("echo '*                                                            *'")
  system("echo '**************************************************************'")

  # Puppetlabs blank ubuntu box
  config.vm.box = "puppetlabs/ubuntu-14.04-64-nocm"

  # Use cache if the plugin vagrant-cachier has been installed
  if Vagrant.has_plugin?("vagrant-cachier")
    config.cache.scope = :box
  end

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine. In the example below,
  # accessing "localhost:8080" will access port 80 on the guest machine.
  # config.vm.network "forwarded_port", guest: 80, host: 8080

  # Create a private network, which allows host-only access to the machine
  # using a specific IP.
  config.vm.network "private_network", ip: "192.168.2.20"

  # Create a public network, which generally matched to bridged network.
  # Bridged networks make the machine appear as another physical device on
  # your network.
  # config.vm.network "public_network"

  # Share an additional folder to the guest VM. The first argument is
  # the path on the host to the actual folder. The second argument is
  # the path on the guest to mount the folder.
  # config.vm.synced_folder "../data", "/vagrant_data"

  # Setup VirtualBox:
  #
  config.vm.provider "virtualbox" do |vb|
    #   # Display the VirtualBox GUI when booting the machine
    #   vb.gui = true
    # Customize the amount of memory on the VM:
    vb.memory = "1024"
  end
  #
  # Provisioning of the VM. Run the setup script. Then run r10k to install puppet modules. Then run the puppet
  # for the environment you wish to setup.
  #
  config.vm.provision :shell, :path => '../../scripts/ubuntu/setup.sh'
  config.vm.provision :shell, :inline => 'cd /tmp/vagrant-puppet/environments/datashield_db_server && r10k -v info puppetfile install'
  config.vm.provision "puppet" do |puppet|
    puppet.environment_path = "../../puppet/environments"
    puppet.environment = "datashield_db_server"
  end
end
