# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrant configuration file for a Ubuntu VM running a datashield server as provisioned by the datashield_testdata
# puppet environment, the VM will be run on the Google computer cloud.
#
# You can specify the Google Cloud Engine setting by setting these authentication shell variables:
#
# export GOOGLE_CLIENT_EMAIL="your-google_service_account_email@developer.gserviceaccount.com"
# export GOOGLE_PROJECT_ID="your-google-cloud-project-id"
# export GOOGLE_JSON_KEY_LOCATION="/full/path/to/your/private-key.json"
#

Vagrant.configure(2) do |config|
  # See https://docs.vagrantup.com. for vagrant config info

  config.vm.box = "google/gce"

  #
  # Setup Google:
  #
  config.vm.provider :google do |google, override|
    google.google_project_id        = "YOUR_GOOGLE_CLOUD_PROJECT_ID"
    google.google_json_key_location = "/path/to/your/private-key.json"

    # Set as required
    override.ssh.username         = "testuser"
    override.ssh.private_key_path = "/home/testuser/.ssh/id_rsa"

    # Make sure to set this to trigger the zone_config
    google.zone = "europe-west2-a" # Zone where the computer is going to be (keep all computers in the same zoon)

    google.zone_config "europe-west2-a" do |zone1f|
      zone1f.name         = "datashield-testdata-ubuntu" # Name of the VM to spin up
      zone1f.image_family = "ubuntu-1604-lts"            # Image of the VM to spin up
      zone1f.machine_type = "n1-standard-1"              # Google cloud compute machine type
      zone1f.zone         = "europe-west2-a"             # Keep this the same as zone
      zone1f.disk_size    = 10                           # Size of the disk (GB)
    end
  end

  #
  # Provisioning of the VM. Run the setup script. Then run r10k to install puppet modules. Then run the puppet
  # for the environment you wish to setup.
  #
  config.vm.provision :shell, :path => '../../scripts/ubuntu/setup.sh'
  config.vm.provision :shell, :inline => 'cd /tmp/vagrant-puppet/environments/datashield_testdata && r10k -v info puppetfile install'
  config.vm.provision "puppet" do |puppet|
    puppet.environment_path = "../../puppet/environments"
    puppet.environment = "datashield_testdata"
  end
end
