# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrant configuration file for a Ubuntu VM running a datashield server as provisioned by the datashield_testdata
# puppet environment, the VM will be run on the Google computer cloud.
#
# vagrant up --provider=google
#

Vagrant.configure(2) do |config|
  # See https://docs.vagrantup.com. for vagrant config info

  config.vm.box = "google/gce"

  # Setup Google:
  #
  config.vm.provider :google do |google, override|
    # Set as required
    # override.ssh.username           = "username"
    # override.ssh.private_key_path   = "/home/username/.ssh/id_rsa"
    # google.google_project_id        = "datashield-d2k"
    # google.google_json_key_location = "/home/username/datashield-d2k.json"

    # Make sure to set this to trigger the zone_config
    google.zone = "europe-west2-a" # Zone where the computer is going to be (keep all computers in the same zoon)

    google.zone_config "europe-west2-a" do |zone1f|
      zone1f.name         = "datashield-testdata-ubuntu" # Name of the VM to spin up
      zone1f.image_family = "ubuntu-1604-lts"            # Image family of the VM to spin up
      zone1f.machine_type = "n1-standard-1"              # Google cloud compute machine type
      zone1f.zone         = "europe-west2-a"             # Keep this the same as zone
      zone1f.disk_size    = 10                           # Size of the disk (GB)
      zone1f.network      = "server-internal"            # Which network for the VM to use
      zone1f.subnetwork   = "server-internal"            # Which subnetwork for the VM to use
    end
  end

  #
  # Provisioning of the VM. Run the setup script. Then run r10k to install puppet modules. Then run the puppet
  # for the environment you wish to setup.
  #
  config.vm.provision :shell, :path => '../../scripts/ubuntu/setup.sh'
  config.vm.provision :shell, :inline => 'cd /tmp/vagrant-puppet/environments/datashield_testdata && r10k -v info puppetfile install'
  config.vm.provision "puppet" do |puppet|
    puppet.environment_path = "../../puppet/environments"
    puppet.environment = "datashield_testdata"
  end
end
